const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');await page.waitForSelector('#source');
 await page.waitForFunction(()=>document.querySelector('#source').value.length>0);
 await page.waitForFunction(()=>document.querySelector('#outputAudio').duration>0);
 const before=await page.evaluate(async()=>await (await fetch('/api/status')).json());
 await page.locator('#rerender').click();
 await page.waitForFunction(()=>document.querySelector('#taskMessage').textContent==='已完成',{},{timeout:120000});
 await page.waitForFunction(()=>!document.querySelector('#rerender').disabled);
 const bundle=await page.locator('#downloadBundle').getAttribute('href');
 const download=await page.request.get('http://127.0.0.1:8765'+bundle);
 if(!download.ok()||(await download.body()).subarray(0,2).toString()!=='PK')throw Error('Bundle download failed');
 const after=await page.evaluate(async()=>await (await fetch('/api/status')).json());
 if(before.spent_estimate!==after.spent_estimate)throw Error('Free render changed spending');
 await page.screenshot({path:'tmp/studio-desktop.png',fullPage:true});
 await page.locator('[data-view="calibration"]').click();
 await page.locator('#startCalibration').click();
 await page.waitForFunction(()=>!document.querySelector('#submitFeedback').disabled,{},{timeout:90000});
 await page.locator('#guess').selectOption('front');
 await page.locator('#feedbackNotes').fill('自动化界面验证，非用户听感评价');
 await page.locator('#submitFeedback').click();
 await page.waitForFunction(()=>document.querySelector('#feedbackResult').textContent.includes('已保存'));
 await page.screenshot({path:'tmp/studio-calibration.png',fullPage:true});
 await page.locator('[data-view="settings"]').click();
 await page.waitForSelector('#assetList .asset-row');
 await page.screenshot({path:'tmp/studio-settings.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.locator('[data-view="workspace"]').click();
 await page.screenshot({path:'tmp/studio-mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 console.log(JSON.stringify({errors,mobileOverflow:overflow,freeRender:true,bundleDownload:true,spent:after.spent_estimate},null,2));
 await browser.close();if(errors.length||overflow)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
