const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const directions={front:'前方',back:'后方',up:'上方',down:'下方',left:'左侧',right:'右侧',near:'近处',far:'远处',move:'左 → 右移动'};
const kinds={speech:'台词',sfx:'音效',ambience:'环境',music:'配乐'};
const emotions={neutral:'自动',happy:'高兴',sad:'悲伤',angry:'愤怒',fearful:'害怕',disgusted:'厌恶',surprised:'惊讶',calm:'平静'};
let project=null,assets=[],voices=[],selected=null,busy=false,profile='H3',direction='front',trial=null,toastTimer=null,dirty=false;
async function api(path,method='GET',body){
 const options={method};if(body!==undefined){options.headers={'Content-Type':'application/json'};options.body=JSON.stringify(body)}
 let r;
 try{r=await fetch('/api'+path,options)}catch{
  throw Error('无法连接本机工作台服务。请双击项目文件夹中的「启动工作台.cmd」，待服务启动后重试。当前填写内容仍保留；这不是 API Key 校验失败。');
 }
 const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;
}
function notify(text,error=false){$('toast').textContent=text;$('toast').style.background=error?'#763e30':'#303e29';$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,error?10000:4000)}
function action(fn){return async(...args)=>{try{await fn(...args)}catch(e){notify(e.message,true)}}}
function options(map,value){return Object.entries(map).map(([k,v])=>`<option value="${esc(k)}" ${k===String(value)?'selected':''}>${esc(v)}</option>`).join('')}
function currentEvent(){return project?.events.find(e=>e.id===selected)}
function markDirty(){dirty=true;$('saveProject').textContent='保存工程 ·';}
async function refreshStatus(){const s=await api('/status');voices=s.voices;$('budgetLabel').textContent=`费用预估 ¥${s.spent_estimate.toFixed(3)} / ¥${s.budget}`;$('serviceStatus').textContent=s.deepseek_configured&&s.minimax_configured?'模型服务已配置':'先试听，再配置模型';$('profiles').innerHTML=s.profiles.map(p=>`<button class="profile ${p.id===profile?'selected':''}" data-profile="${p.id}" ${p.available?'':'disabled'}><strong>${p.id}</strong><span>${p.available?'SADIE 实测配置':'数据未安装'}</span></button>`).join('');}
async function refreshProjects(){const rows=await api('/projects');$('projects').innerHTML=rows.map(p=>`<button data-project="${p.id}" class="${project?.id===p.id?'active':''}">${esc(p.title)}</button>`).join('')}
function renderProject(){
 $('projectTitle').value=project.title;$('source').value=project.source;$('charCount').textContent=`${project.source.length} / 2000`;
 document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===project.mode));
 renderCharacters();renderEvents();renderInspector();renderOutputs();$('projectNotes').textContent=project.notes.join(' / ');dirty=false;$('saveProject').textContent='保存工程';refreshEstimate();
}
async function openProject(id){if(dirty)await save();project=await api('/projects/'+id);selected=project.events[0]?.id||null;renderProject();await refreshProjects()}
async function newProject(example=false){if(dirty)await save();const data=example?await api('/example'):{title:'未命名场景',source:''};project=await api('/projects','POST',data);selected=null;renderProject();await refreshProjects()}
async function save(){if(!project)return;const invalid=project.events.map((e,i)=>({e,i})).filter(({e})=>!Number.isFinite(e.gain_db)||e.gain_db < -48||e.gain_db > 6);if(invalid.length)throw Error(`第${invalid.map(({i})=>i+1).join('、')}条事件音量超出范围，请填写 −48～+6 dB（不是百分比），再保存或渲染。`);project=await api('/projects/'+project.id,'PUT',project);dirty=false;$('saveProject').textContent='保存工程';await refreshProjects();await refreshEstimate()}
async function refreshEstimate(){if(!project)return;const e=await api(`/projects/${project.id}/estimate`);$('estimate').textContent=e.uncached_utterances?`配音预估 ¥${e.tts_estimate.toFixed(3)}`:project.events.length?'已有配音可免费复用':'等待脚本'}
function renderCharacters(){
 $('characterCount').textContent=project.characters.length;
 $('characters').innerHTML=project.characters.map(c=>`<div class="character" data-character="${c.id}"><input aria-label="角色名" data-char-field="name" value="${esc(c.name)}"><select aria-label="音色" data-char-field="voice">${options(Object.fromEntries([...voices,...(voices.some(v=>v[0]===c.voice)?[]:[[c.voice,c.voice]])]),c.voice)}</select></div>`).join('');
}
function renderEvents(){
 $('eventCount').textContent=project.events.length;
 if(!project.events.length){$('events').innerHTML='<div class="empty"><span class="empty-symbol">≋</span><h3>让故事拥有空间</h3><p>生成声音脚本后，在这里编辑每一个声音。</p></div>';return}
 $('events').innerHTML=project.events.map((e,i)=>{const c=project.characters.find(c=>c.id===e.character_id);const a=assets.find(a=>a.id===e.asset_id);return `<button class="event ${selected===e.id?'selected':''} ${e.enabled?'':'off'}" data-event="${e.id}"><span class="event-number">${String(i+1).padStart(2,'0')}</span><span class="event-content"><strong>${esc(e.kind==='speech'?c?.name||'未指定':a?.name||'请选择素材')}</strong><p>${esc(e.text||e.original||`${directionsFor(e.points[0])} · ${e.duration||'原长'}秒`)}</p></span><span class="event-meta">${kinds[e.kind]}<br>${e.start==null?'自动':e.start.toFixed(1)+'s'}</span></button>`}).join('');
}
function directionsFor(p){if(!p)return'前方';return `${p.x<0?'左':p.x>0?'右':''}${p.z<0?'后':p.z>0?'前':''}${p.y>0?'上':p.y<0?'下':''} ${Math.hypot(p.x,p.y,p.z).toFixed(1)}m`}
function renderStage(e){const ps=e?.points||[{x:0,y:0,z:2}];const xy=p=>[150+Math.max(-5,Math.min(5,p.x))*20,120-Math.max(-5,Math.min(5,p.z))*20];const [x,y]=xy(ps[0]);$('sourceDot').setAttribute('cx',x);$('sourceDot').setAttribute('cy',y);$('trajectoryLine').setAttribute('d',ps.map((p,i)=>(i?'L':'M')+xy(p).join(' ')).join(' '));$('positionLabel').textContent=e?`${directionsFor(ps[0])} · 高度 ${ps[0].y}m`:'固定旁观视角'}
function renderInspector(){
 const e=currentEvent();renderStage(e);if(!e){$('inspector').innerHTML='<p class="muted">选中一条声音事件，修改它的内容与位置。</p>';return}
 const field=(name,label,html)=>`<label>${label}${html}</label>`;
 const input=(name,value,type='text',extra='')=>`<input data-field="${name}" type="${type}" value="${esc(value)}" ${extra}>`;
 const select=(name,map,value)=>`<select data-field="${name}">${options(map,value)}</select>`;
 let html=`<label class="checkbox"><input type="checkbox" data-field="enabled" ${e.enabled?'checked':''}>启用此事件</label>`;
 if(e.kind==='speech'){
  html+=field('character_id','说话人',select('character_id',Object.fromEntries(project.characters.map(c=>[c.id,c.name])),e.character_id));
  html+=field('text','台词',`<textarea rows="3" data-field="text">${esc(e.text)}</textarea>`);
  html+=`<details><summary>查看原文 / 恢复</summary><p class="hint">${esc(e.original)}</p><button class="text-button" id="restoreOriginal">恢复原文</button></details>`;
  html+=`<div class="two-col">${field('emotion','情绪',select('emotion',emotions,e.emotion))}${field('speed','语速',input('speed',e.speed,'number','min="0.5" max="2" step="0.05"'))}</div>`;
 }else{
  html+=field('kind','类型',select('kind',{sfx:'点声源音效',ambience:'循环环境音',music:'循环配乐'},e.kind));
  html+=field('duration','时长 / 秒',input('duration',e.duration||'','number','min="0.1" max="180" step="0.1" placeholder="使用素材原长"'));
  html+=field('anchor_id','关联台词',select('anchor_id',{'':'无锚点',...Object.fromEntries(project.events.filter(x=>x.kind==='speech').map(x=>[x.id,x.text.slice(0,18)||'已替换的原文']))},e.anchor_id));
  html+=`<div class="two-col">${field('placement','相对位置',select('placement',{before:'句前',after:'句后',within:'句内',absolute:'绝对时间'},e.placement))}${field('offset','偏移 / 秒',input('offset',e.offset,'number','min="0" max="1200" step="0.1"'))}</div>`;
 }
 html+=field('asset_id',e.kind==='speech'?'录音替代配音（可选）':'音频素材',select('asset_id',{'':e.kind==='speech'?'使用模型配音':'请选择素材',...Object.fromEntries(assets.map(a=>[a.id,a.name]))},e.asset_id));
 if(e.asset_id)html+=`<audio controls preload="none" style="width:100%;height:30px" src="/api/assets/${encodeURIComponent(e.asset_id)}/audio"></audio>`;
 html+=`<div class="two-col">${field('start','开始时间 / 秒',input('start',e.start??'','number','min="0" max="1200" step="0.1" placeholder="自动编排"'))}${field('gain_db','音量 / dB（−48～+6）',input('gain_db',e.gain_db,'number','min="-48" max="6" step="0.1"'))}</div><p class="hint">0 dB 保持原音量，负数减小，正数放大；这里不是百分比。</p>`;
 html+='<h3>空间位置 / 米</h3><div class="three-col">'+['x','y','z'].map((k,i)=>`<label>${['右 + / 左 −','上 + / 下 −','前 + / 后 −'][i]}<input data-point="${k}" type="number" value="${e.points[0][k]}" min="-${k==='y'?20:50}" max="${k==='y'?20:50}" step="0.25"></label>`).join('')+'</div>';
 html+=`<details><summary>移动轨迹 · ${e.points.length} 个点</summary><p class="hint">每行：时间, x, y, z；首行时间为0，其余递增。</p><textarea id="trajectoryInput" rows="4">${e.points.map(p=>[p.t,p.x,p.y,p.z].join(', ')).join('\n')}</textarea><button id="applyTrajectory" class="text-button">应用轨迹</button></details><button class="text-button danger" id="deleteEvent">删除此事件</button>`;
 $('inspector').innerHTML=html;
}
function renderOutputs(){const outputs=project.outputs;$('outputHistory').innerHTML=outputs.length?[...outputs].reverse().map(o=>`<option value="${o.id}">${new Date(o.created_at*1000).toLocaleString()} · 版本 ${o.revision}</option>`).join(''):'<option>尚无成品</option>';if(outputs.length)showOutput(outputs.at(-1).id);else{$('outputAudio').removeAttribute('src');$('outputAudio').load();$('outputMeta').textContent='完成渲染后，音频将出现在这里。';for(const id of ['downloadWav','downloadBundle','downloadReport','downloadCsv']){$(id).classList.add('disabled');$(id).removeAttribute('href')}}}
function showOutput(id){const o=project.outputs.find(o=>o.id===id);if(!o)return;$('outputAudio').src=`/api/renders/${id}/audio`;$('outputMeta').textContent=`${o.metrics.duration.toFixed(1)} 秒 · ${o.metrics.profile} · ${o.revision===project.revision?'当前工程':'历史版本，修改后需重新渲染'}`;$('downloadWav').href=`/api/renders/${id}/audio`;$('downloadWav').download=project.title+'.wav';$('downloadReport').href=`/api/renders/${id}/report`;$('downloadCsv').href=`/api/renders/${id}/csv`;$('downloadReport').download='声音脚本.html';$('downloadCsv').download='声音脚本.csv';$('downloadBundle').href=`/api/renders/${id}/bundle`;for(const k of ['downloadWav','downloadBundle','downloadReport','downloadCsv'])$(k).classList.remove('disabled')}
function setBusy(value){busy=value;for(const id of ['analyze','localDraft','generate','rerender','saveProject','newProject','loadExample','startCalibration'])$(id).disabled=value;document.querySelectorAll('#workspace input,#workspace textarea,#workspace select,#workspace .text-button,#workspace [data-mode],#projects button').forEach(b=>b.disabled=value)}
async function waitJob(job,onComplete){setBusy(true);try{let value=job;while(['queued','running'].includes(value.status)){$('taskMessage').textContent=value.message;$('taskProgress').value=value.progress;$('taskPercent').textContent=Math.round(value.progress*100)+'%';await new Promise(r=>setTimeout(r,900));value=await api('/jobs/'+job.id)}$('taskMessage').textContent=value.message;$('taskProgress').value=value.progress;$('taskPercent').textContent=value.status==='complete'?'100%':'';if(value.status!=='complete')throw Error(value.message);await onComplete(value.result);await refreshStatus();notify('已完成')}finally{setBusy(false)}}
async function runScript(online){if(!project.source.trim())throw Error('请先输入文本');await save();const job=await api(`/projects/${project.id}/script`,'POST',{online});await waitJob(job,async()=>{project=await api('/projects/'+project.id);selected=project.events[0]?.id;renderProject()})}
async function runGenerate(allow_paid){await save();const job=await api(`/projects/${project.id}/generate`,'POST',{allow_paid});await waitJob(job,async()=>{project=await api('/projects/'+project.id);renderOutputs();await refreshEstimate()})}
async function view(name){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===name));document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===name));$('pageTitle').textContent={workspace:'声音，从这里发生。',calibration:'空间试听',settings:'服务与费用'}[name];$('saveProject').hidden=name!=='workspace';if(name==='settings')await renderSettings();if(name==='calibration')await feedbackHistory()}
async function renderSettings(){const s=await api('/settings');for(const [key,value]of Object.entries(s)){const el=$('settingsForm').elements[key];if(el){if(el.type==='checkbox')el.checked=value;else el.value=value}}const rows=await api('/ledger');$('ledger').innerHTML=rows.length?rows.reverse().map(r=>`<div class="ledger-row"><span>${esc(r.provider)}<small>${new Date(r.timestamp*1000).toLocaleString()} · ${esc(r.status)}</small></span><strong>¥${r.charged_estimate.toFixed(4)}</strong></div>`).join(''):'<p class="hint">尚无付费调用。</p>';renderAssets()}
function renderAssets(){$('assetList').innerHTML=assets.map(a=>`<div class="asset-row"><span>${esc(a.name)}<small>${esc(a.license)} · ${a.duration.toFixed(1)}s<br>${esc(a.source)}</small></span><button class="text-button" data-preview="${a.id}">试听</button></div>`).join('')}
async function feedbackHistory(){const rows=await api('/calibration-results');$('feedbackHistory').innerHTML=rows.length?rows.reverse().map(r=>`<div class="feedback-row"><span>${esc(r.profile)} · 实际${esc(directions[r.direction])} / 判断${esc(directions[r.feedback.guess]||r.feedback.guess)}</span><span>${r.feedback.rating}/5 · ${esc(r.feedback.notes)}</span></div>`).join(''):'<p class="hint">尚无记录。</p>'}

$('source').addEventListener('input',()=>{project.source=$('source').value;project.events=[];project.characters=[];selected=null;markDirty();$('charCount').textContent=`${project.source.length} / 2000`;renderEvents();renderInspector();renderCharacters()});
$('projectTitle').addEventListener('input',()=>{project.title=$('projectTitle').value;markDirty()});
$('saveProject').onclick=action(async()=>{await save();notify('工程已保存')});
$('newProject').onclick=action(()=>newProject());$('loadExample').onclick=action(()=>newProject(true));
$('analyze').onclick=action(()=>runScript(true));$('localDraft').onclick=action(()=>runScript(false));$('generate').onclick=action(()=>runGenerate(true));$('rerender').onclick=action(()=>runGenerate(false));
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=action(()=>view(b.dataset.view)));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(project.mode===b.dataset.mode)return;project.mode=b.dataset.mode;project.events=[];project.characters=[];selected=null;renderProject();markDirty();notify('模式已切换，请重新生成声音脚本')});
$('projects').onclick=action(async ev=>{const b=ev.target.closest('[data-project]');if(b&&!busy)await openProject(b.dataset.project)});
$('events').onclick=ev=>{const b=ev.target.closest('[data-event]');if(b){selected=b.dataset.event;renderEvents();renderInspector();if(busy)setBusy(true)}};
$('characters').addEventListener('change',ev=>{const field=ev.target.dataset.charField;if(field){const c=project.characters.find(c=>c.id===ev.target.closest('[data-character]').dataset.character);c[field]=ev.target.value;markDirty();renderEvents();renderInspector()}});
$('addCharacter').onclick=()=>{if(busy)return;project.characters.push({id:'c'+crypto.randomUUID().replaceAll('-',''),name:'新角色',voice:voices[project.characters.length%voices.length][0]});markDirty();renderCharacters();renderInspector()};
$('addEffect').onclick=()=>{if(busy)return;const e={id:'fx'+crypto.randomUUID().replaceAll('-',''),kind:'sfx',character_id:'',text:'',original:'',source_start:0,source_end:0,emotion:'neutral',speed:1,asset_id:'',anchor_id:project.events.find(e=>e.kind==='speech')?.id||'',placement:'after',offset:0,start:null,duration:null,gain_db:-12,points:[{t:0,x:0,y:0,z:2}],enabled:true};project.events.push(e);selected=e.id;markDirty();renderEvents();renderInspector()};
$('inspector').addEventListener('change',ev=>{if(busy)return;const el=ev.target,e=currentEvent();if(!e)return;if(el.dataset.field){const f=el.dataset.field;if(f==='gain_db'&&(el.value===''||!Number.isFinite(Number(el.value))||Number(el.value)<-48||Number(el.value)>6)){el.value=e.gain_db;notify('音量只能填写 −48～+6 dB，已保留修改前的值。这里不是百分比。',true);return}e[f]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:Number(el.value)):el.value;markDirty();renderEvents();if(['kind','asset_id'].includes(f))renderInspector()}if(el.dataset.point){e.points[0][el.dataset.point]=Number(el.value);markDirty();renderStage(e);renderEvents()}});
$('inspector').onclick=action(async ev=>{if(busy)return;const e=currentEvent();if(!e)return;if(ev.target.id==='restoreOriginal'){e.text=e.original;e.enabled=true;e.asset_id='';markDirty();renderEvents();renderInspector()}if(ev.target.id==='deleteEvent'){project.events=project.events.filter(x=>x.id!==e.id);project.events.forEach(x=>{if(x.anchor_id===e.id)x.anchor_id=''});selected=project.events[0]?.id;markDirty();renderEvents();renderInspector()}if(ev.target.id==='applyTrajectory'){const ps=$('trajectoryInput').value.trim().split('\n').map(row=>row.split(',').map(Number));if(!ps.length||ps.some(p=>p.length!==4||p.some(v=>!Number.isFinite(v)))||ps[0][0]!==0||ps.some((p,i)=>i&&p[0]<=ps[i-1][0]))throw Error('每行填写时间,x,y,z；从0秒开始，时间严格递增');e.points=ps.map(([t,x,y,z])=>({t,x,y,z}));markDirty();renderInspector();renderEvents()}});
$('outputHistory').onchange=()=>showOutput($('outputHistory').value);
$('settingsForm').onsubmit=action(async ev=>{ev.preventDefault();const form=new FormData(ev.target),data=Object.fromEntries(form);for(const key of ['input_per_million','output_per_million','tts_per_10k','budget'])data[key]=Number(data[key]);data.rates_confirmed=form.has('rates_confirmed');await api('/settings','PUT',data);ev.target.elements.deepseek_key.value='';ev.target.elements.minimax_key.value='';await refreshStatus();notify('服务设置已保存')});
$('settingsForm').elements.tts_model.onchange=ev=>{$('settingsForm').elements.tts_per_10k.value=ev.target.value.endsWith('hd')?3.5:2;$('settingsForm').elements.rates_confirmed.checked=false};
$('upload').onchange=action(async ev=>{const file=ev.target.files[0];if(!file)return;const form=new FormData();form.append('file',file);const r=await fetch('/api/assets',{method:'POST',body:form}),v=await r.json();if(!r.ok)throw Error(v.detail);assets=await api('/assets');renderAssets();renderInspector();notify('素材已导入');ev.target.value=''});
let previewAudio=new Audio();$('assetList').onclick=action(async ev=>{const b=ev.target.closest('[data-preview]');if(b){previewAudio.pause();previewAudio.src='/api/assets/'+b.dataset.preview+'/audio';await previewAudio.play()}});
$('directions').innerHTML=Object.entries(directions).map(([k,v])=>`<button data-direction="${k}" class="${k===direction?'selected':''}">${v}</button>`).join('');$('guess').innerHTML=options({...directions,unclear:'不确定'},'unclear');
$('directions').onclick=ev=>{const b=ev.target.closest('[data-direction]');if(b){direction=b.dataset.direction;document.querySelectorAll('[data-direction]').forEach(el=>el.classList.toggle('selected',el.dataset.direction===direction))}};
$('profiles').onclick=action(async ev=>{const b=ev.target.closest('[data-profile]');if(b&&!b.disabled){profile=b.dataset.profile;await refreshStatus()}});
$('useProfile').onclick=action(async()=>{project.render.profile=profile;project.render.room=Number($('calRoom').value);markDirty();await save();notify('已应用配置；已有成品需重新渲染')});
$('startCalibration').onclick=action(async()=>{trial=null;$('submitFeedback').disabled=true;$('feedbackResult').textContent='';$('trialLabel').textContent='正在渲染试听片段…';const blind=$('blind').checked;const job=await api('/calibration','POST',{profile,direction,room:Number($('calRoom').value),blind});await waitJob(job,async r=>{trial=r.trial;$('calAudio').src=r.audio;$('trialLabel').textContent=blind?'盲听 · 请判断方向':directions[r.direction];$('submitFeedback').disabled=false;try{await $('calAudio').play()}catch{notify('点击播放器开始试听')}})});
$('submitFeedback').onclick=action(async()=>{if(!trial)throw Error('请先生成试听片段');const r=await api(`/calibration/${trial}/feedback`,'POST',{guess:$('guess').value,rating:Number($('rating').value),notes:$('feedbackNotes').value});$('feedbackResult').textContent=`已保存 · 实际方向：${directions[r.direction]} · ${r.correct?'判断一致':'已记录差异'}`;$('submitFeedback').disabled=true;await feedbackHistory()});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
action(async()=>{await refreshStatus();assets=await api('/assets');const rows=await api('/projects');if(rows.length)await openProject(rows[0].id);else await newProject(true);const jobs=await api('/jobs');const active=jobs.find(j=>['queued','running'].includes(j.status)&&j.project_id===project.id);if(active)await waitJob(active,async()=>{project=await api('/projects/'+project.id);renderProject()})})();
